name: merchandise_product_analytics
version: '1.0.0'
config-version: 2
profile: merchandise_product_analytics
model-paths: [models]
test-paths: [tests]
models:
  merchandise_product_analytics:
    +materialized: table
    +tags: [historical_ga4]
