-- Generated by scripts/sync_dbt.py. Edit canonical sql/ source.
-- Sequential session funnel uses strict timestamps; equal-time order is unknown.
-- User reach is unordered and intentionally NOT described as a sequential funnel.
WITH session_counts AS (
 SELECT 'ordered_sessions' AS grain, stage, COUNTIF(reached) AS reached
 FROM {{ ref('int_sessions') }}, UNNEST([
   STRUCT(1 AS stage, view_ts IS NOT NULL AS reached), STRUCT(2,cart_ts IS NOT NULL),
   STRUCT(3,checkout_ts IS NOT NULL), STRUCT(4,purchase_ts IS NOT NULL)]) GROUP BY stage
), user_counts AS (
 SELECT 'unordered_users' AS grain,
 CASE event_name WHEN 'view_item' THEN 1 WHEN 'add_to_cart' THEN 2 WHEN 'begin_checkout' THEN 3 ELSE 4 END AS stage,
 COUNT(DISTINCT user_pseudo_id) AS reached
 FROM {{ ref('stg_events') }} WHERE valid_user AND event_name IN ('view_item','add_to_cart','begin_checkout','purchase')
 GROUP BY stage
), counts AS (SELECT * FROM session_counts UNION ALL SELECT * FROM user_counts),
previous AS (SELECT *, LAG(reached) OVER(PARTITION BY grain ORDER BY stage) AS previous_reached,
 FIRST_VALUE(reached) OVER(PARTITION BY grain ORDER BY stage) AS entrants FROM counts)
SELECT *, IF(grain='ordered_sessions',SAFE_DIVIDE(reached,previous_reached),NULL) AS step_conversion,
 IF(grain='ordered_sessions',previous_reached-reached,NULL) AS dropoff,
 IF(grain='ordered_sessions',SAFE_DIVIDE(previous_reached-reached,previous_reached),NULL) AS dropoff_rate,
 IF(grain='ordered_sessions',SAFE_DIVIDE(reached,entrants),NULL) AS total_conversion FROM previous
