"""Generate dbt's copies from canonical SQL; --check detects drift in CI."""

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()


def parameterize(content):
    """dbt vars match the direct runner while historical canonical SQL stays intact."""
    return (content.replace("'20201101'", "'{{ var(\"start_date\", \"2020-11-01\") | replace(\"-\", \"\") }}'")
            .replace("'20210131'", "'{{ var(\"end_date\", \"2021-01-31\") | replace(\"-\", \"\") }}'")
            .replace("DATE '2020-11-01'", "DATE '{{ var(\"start_date\", \"2020-11-01\") }}'")
            .replace("DATE '2021-01-31'", "DATE '{{ var(\"end_date\", \"2021-01-31\") }}'")
            .replace("ABS(92-COUNT", "ABS((DATE_DIFF(DATE '{{ var(\"end_date\", \"2021-01-31\") }}', DATE '{{ var(\"start_date\", \"2020-11-01\") }}', DAY)+1)-COUNT"))


for folder in ["staging", "intermediate", "marts"]:
    for source in (ROOT / "sql" / folder).glob("*.sql"):
        target = ROOT / "dbt/models" / folder / source.name
        content = "-- Generated by scripts/sync_dbt.py. Edit canonical sql/ source.\n" + parameterize(source.read_text(
            encoding="utf-8"
        ))
        if args.check:
            assert target.read_text(encoding="utf-8") == content, f"dbt drift: {source.name}"
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8", newline="\n")
quality = parameterize((ROOT / "sql/analyses/quality.sql").read_text(encoding="utf-8"))
content = "WITH checks AS (\n" + quality + "\n) SELECT * FROM checks WHERE failures>0\n"
target = ROOT / "dbt/tests/quality.sql"
if args.check:
    assert target.read_text(encoding="utf-8") == content
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")
keys = {
    "int_sessions": "session_id",
    "int_users": "user_pseudo_id",
    "fct_purchases": "transaction_id",
    "mart_daily_product_metrics": "metric_date",
    "mart_conversion_features": "session_key",
}
schema = {
    "version": 2,
    "models": [
        {"name": model, "columns": [{"name": key, "data_tests": ["unique", "not_null"]}]}
        for model, key in keys.items()
    ],
}
schema["models"] += [
    {
        "name": "mart_retention",
        "columns": [
            {
                "name": "horizon",
                "data_tests": [{"accepted_values": {"values": [1, 7, 14, 30], "quote": False}}],
            }
        ],
    }
]
target = ROOT / "dbt/models/schema.yml"
content = yaml.safe_dump(schema, sort_keys=False)
if args.check:
    assert target.read_text(encoding="utf-8") == content
else:
    target.write_text(content, encoding="utf-8", newline="\n")

source = ROOT / "sql/analyses/model_feature_quality.sql"
content = "WITH checks AS (\n" + source.read_text(encoding="utf-8") + "\n) SELECT * FROM checks WHERE failures>0\n"
target = ROOT / "dbt/tests/model_feature_quality.sql"
if args.check:
    assert target.read_text(encoding="utf-8") == content
else:
    target.write_text(content, encoding="utf-8", newline="\n")
