"""Metric definitions are publication inputs, not prose-only promises."""

METRICS = [
    dict(
        name="Purchasing users",
        grain="user × event date",
        numerator="Distinct valid users with purchase events",
        denominator="None",
        sql="COUNT(DISTINCT IF(valid_user AND event_name='purchase',user_pseudo_id,NULL))",
        exclusions="Missing / placeholder user IDs",
        caveat="North-star candidate; browser IDs are not people. Daily counts are not additive across dates.",
    ),
    dict(
        name="Session conversion",
        grain="session start date",
        numerator="Sessions with a purchase event",
        denominator="Valid observed sessions",
        sql="SAFE_DIVIDE(COUNTIF(purchase_event),COUNT(*))",
        exclusions="Missing user or session ID",
        caveat="Includes purchases without valid transaction IDs; not an ordered funnel rate.",
    ),
    dict(
        name="Checkout completion",
        grain="ordered session funnel",
        numerator="Sessions reaching ordered purchase",
        denominator="Sessions reaching ordered checkout",
        sql="SAFE_DIVIDE(COUNTIF(purchase_ts IS NOT NULL),COUNTIF(checkout_ts IS NOT NULL))",
        exclusions="Missing earlier stages and equal-time transitions",
        caveat="Conservative observable sequence; instrumentation gaps may resemble dropoff.",
    ),
    dict(
        name="Revenue per active user",
        grain="event / purchase date",
        numerator="Deduplicated observed transaction USD revenue",
        denominator="Distinct valid active users",
        sql="SAFE_DIVIDE(revenue_usd,users)",
        exclusions="Invalid transaction IDs; missing USD not imputed",
        caveat="Revenue includes transactions without valid users. Withhold decision use if missing revenue or identity coverage is material.",
    ),
    dict(
        name="Average order value",
        grain="transaction / purchase date",
        numerator="Observed USD revenue",
        denominator="Valid distinct transactions",
        sql="SAFE_DIVIDE(revenue_usd,transactions)",
        exclusions="Invalid IDs",
        caveat="Incomplete if any transaction revenue is missing; gross purchase value, not net refunds.",
    ),
    dict(
        name="Exact-day retention",
        grain="first-observed cohort × horizon",
        numerator="Eligible users active on exact day N",
        denominator="Users with N complete days available",
        sql="SAFE_DIVIDE(returned_users,eligible_users)",
        exclusions="Right-censored users",
        caveat="First observation is not acquisition or signup. Historical left censoring remains.",
    ),
    dict(
        name="Funnel inputs",
        grain="session",
        numerator="Sessions with product view / cart / checkout events",
        denominator="Valid sessions for rates",
        sql="COUNTIF(viewed_item), COUNTIF(added_cart), COUNTIF(began_checkout)",
        exclusions="Invalid session IDs",
        caveat="Unordered presence inputs differ from ordered funnel stage counts.",
    ),
    dict(
        name="Transaction rate",
        grain="session",
        numerator="Deduplicated transactions linked to valid sessions",
        denominator="Valid sessions",
        sql="SAFE_DIVIDE(SUM(transactions),COUNT(*))",
        exclusions="Unlinked transactions",
        caveat="Can exceed one; do not label as conversion probability.",
    ),
]
